"""update photo table again

Revision ID: 4fea54426352
Revises: d6d1c2b24720
Create Date: 2015-12-19 23:41:14.921077

"""

# revision identifiers, used by Alembic.
revision = '4fea54426352'
down_revision = 'd6d1c2b24720'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
