"""Name revision

Revision ID: 71a55bc3b32f
Revises: b5eed04c202
Create Date: 2015-12-23 12:57:50.775300

"""

# revision identifiers, used by Alembic.
revision = '71a55bc3b32f'
down_revision = 'b5eed04c202'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
