"""First for deploy

Revision ID: b5eed04c202
Revises: 
Create Date: 2015-12-23 12:17:09.553060

"""

# revision identifiers, used by Alembic.
revision = 'b5eed04c202'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
