"""Deploy 1.0

Revision ID: c2ad1af4f2d7
Revises: 
Create Date: 2015-12-24 15:50:13.092676

"""

# revision identifiers, used by Alembic.
revision = 'c2ad1af4f2d7'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
