"""update photo table

Revision ID: d6d1c2b24720
Revises: 9bcb91518ed5
Create Date: 2015-12-19 23:16:20.282541

"""

# revision identifiers, used by Alembic.
revision = 'd6d1c2b24720'
down_revision = '9bcb91518ed5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('photo_id', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'photo_id')
    ### end Alembic commands ###
